userLogin/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  resources :users
end

userLogin/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

userLogin/app/models/user.rb
class User < ApplicationRecord
  
end

userLogin/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

userLogin/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end


  def new

  end

  def show
  end

  def create
    @user = Users.new(params)

    @user.save
    redirect_to @user
  end

  private
  def params
    params.require(:user).permit(:email, :password)
  end

end

userLogin/app/helpers/application_helper.rb
module ApplicationHelper
end

userLogin/app/helpers/users_helper.rb
module UsersHelper
end

userLogin/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserLogin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

userLogin/app/views/users/create.html.erb
<h1> This is the create page </h1>

userLogin/app/views/users/index.html.erb
<h1> This is the index page </h1>
<% @user.each do |x| %>
<%= x.email %>
<% end %>
 <% Please log in here if your email doesn't exist %>
 <%= link_to 'LOG IN', users_new_path %>

userLogin/app/views/users/login.html.erb
<h1> This is the login page </h1>
<p>
  <%= form.label :email %><br>
  <%= form.text_field :email%>
</p>

userLogin/app/views/users/new.html.erb
<%= form_with scope: :users, url: users_path, local: true do |form| %>
  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email%>
  </p>

  <p>
    <%= form.label :password %><br>
    <%= form.text_area :password %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

userLogin/app/views/users/show.html.erb
<h1> This is the show page <h1>